INSERT INTO holidays (country_code, date, name_es, name_en, type, is_banking) VALUES
('co', '2025-01-01', 'Año Nuevo',                       'New Year''s Day',       'NATIONAL', true),
('co', '2025-01-06', 'Día de Reyes',                    'Epiphany',              'NATIONAL', true),
('co', '2025-03-24', 'Día de San José',                 'Saint Joseph''s Day',   'NATIONAL', true),
('co', '2025-04-17', 'Jueves Santo',                    'Holy Thursday',         'NATIONAL', true),
('co', '2025-04-18', 'Viernes Santo',                   'Good Friday',           'NATIONAL', true),
('co', '2025-05-01', 'Día del Trabajo',                 'Labor Day',             'NATIONAL', true),
('co', '2025-06-02', 'Día de la Ascensión',             'Ascension Day',         'NATIONAL', true),
('co', '2025-06-23', 'Corpus Christi',                  'Corpus Christi',        'NATIONAL', true),
('co', '2025-06-30', 'Sagrado Corazón de Jesús',        'Sacred Heart',          'NATIONAL', true),
('co', '2025-07-07', 'San Pedro y San Pablo',           'Saints Peter and Paul', 'NATIONAL', true),
('co', '2025-07-20', 'Día de la Independencia',         'Independence Day',      'NATIONAL', true),
('co', '2025-08-07', 'Batalla de Boyacá',               'Battle of Boyacá',      'NATIONAL', true),
('co', '2025-08-18', 'Asunción de la Virgen',           'Assumption of Mary',    'NATIONAL', true),
('co', '2025-10-13', 'Día de la Raza',                  'Columbus Day',          'NATIONAL', true),
('co', '2025-11-03', 'Todos los Santos',                'All Saints Day',        'NATIONAL', true),
('co', '2025-11-17', 'Independencia de Cartagena',      'Cartagena Independence','NATIONAL', true),
('co', '2025-12-08', 'Inmaculada Concepción',           'Immaculate Conception', 'NATIONAL', true),
('co', '2025-12-25', 'Navidad',                         'Christmas Day',         'NATIONAL', true);